version: "3"

services:
  api_server:
    container_name: api
    build:
      context: .
      dockerfile: ./api-server/Dockerfile.dev
    ports:
      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE:
#      SPRING_DATASOURCE_URL:
#      SPRING_DATASOURCE_USERNAME:
#      SPRING_DATASOURCE_PASSWORD:
#      SPRING_DATA_MONGODB_DATABASE:
#      SPRING_DATA_MONGODB_HOST:
#      SPRING_DATA_MONGODB_PORT:
#      SPRING_DATA_MONGODB_USERNAME:
#      SPRING_DATA_MONGODB_PASSWORD:
  chat_server:
    container_name: chat
    build:
      context: .
      dockerfile: ./chat-server/Dockerfile.dev
    ports:
      - "8880:8880"
#    environment:
#      SPRING_PROFILES_ACTIVE:
#      SPRING_DATASOURCE_URL:
#      SPRING_DATASOURCE_USERNAME:
#      SPRING_DATASOURCE_PASSWORD:
#      SPRING_DATA_MONGODB_DATABASE:
#      SPRING_DATA_MONGODB_HOST:
#      SPRING_DATA_MONGODB_PORT:
#      SPRING_DATA_MONGODB_USERNAME:
#      SPRING_DATA_MONGODB_PASSWORD:

networks:
  default:
    external:
      name: daangn_net