version: "3"

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29095:9095"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9095,PLAINTEXT_HOST://localhost:29095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  api_server:
    container_name: api
    build:
      context: .
      dockerfile: ./api-server/Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
  #      SPRING_DATASOURCE_HIKARI_DRIVERCLASSNAME:
  #      SPRING_DATASOURCE_HIKARI_JDBCURL:
  #      SPRING_DATASOURCE_HIKARI_USERNAME:
  #      SPRING_DATASOURCE_HIKARI_PASSWORD:
  #      SPRING_DATA_MONGODB_DATABASE:
  #      SPRING_DATA_MONGODB_URI:
  chat_server:
    container_name: chat
    build:
      context: .
      dockerfile: ./chat-server/Dockerfile.dev
    ports:
      - "9080:9080"
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: dev
#      SPRING_DATASOURCE_HIKARI_DRIVERCLASSNAME:
#      SPRING_DATASOURCE_HIKARI_JDBCURL:
#      SPRING_DATASOURCE_HIKARI_USERNAME:
#      SPRING_DATASOURCE_HIKARI_PASSWORD:
#      SPRING_DATA_MONGODB_DATABASE:
#      SPRING_DATA_MONGODB_URI:

networks:
  default:
    external:
      name: daangn_net