spring:
  profiles:
    active: local

server:
  port: 9080

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      #      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;
      jdbc-url: jdbc:h2:tcp://localhost/~/daangn;MODE=MYSQL;
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  data:
    mongodb:
      database: daangn_test
      port: 27017
      host: localhost
#      authentication-database: admin

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: production