spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

server:
  port: 9080

jwt:
  header: api_key
  issuer: daangn-server
  client-secret: daangn-server
  expiry-seconds: 7200 # 2시간

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/daangn;MODE=MYSQL;DB_CLOSE_DELAY=-1
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    mongodb:
      database: daangn_test
      uri: mongodb://localhost:27017/daangn_test

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never # schema.sql 실행 금지

---
spring:
  config:
    activate:
      on-profile: production