spring:
  profiles:
    active: local

jwt:
  header: api_key
  issuer: daangn-server
  client-secret: daangn-server
  expiry-seconds: 7200 # 2시간

oauth:
  kakao:
    header-key: Authorization
    header-value: Bearer
    login-url: https://kapi.kakao.com/v2/user/me
    logout-url: https://kapi.kakao.com/v1/user/logout

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;
      jdbc-url: jdbc:h2:tcp://localhost/~/daangn;MODE=MYSQL;
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  data:
    mongodb:
      database: daangn_test
      port: 27017
      host: localhost
      authentication-database: admin
  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never # schema.sql 실행 금지
---
spring:
  config:
    activate:
      on-profile: production