spring:
  profiles:
    active: local

jwt:
  header: api_key
  issuer: daangn-server
  client-secret: daangn-server
  expiry-seconds: 7200 # 2시간

oauth:
  kakao:
    header-key: Authorization
    header-value: Bearer
    login-url: https://kapi.kakao.com/v2/user/me
    logout-url: https://kapi.kakao.com/v1/user/logout

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    initialize: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

server:
  port: 9080

---
spring:
  config:
    activate:
      on-profile: production