insert into categories(name) values('디지털기기');
insert into categories(name) values('생활가전');
insert into categories(name) values('가구/인테리어');
insert into categories(name) values('유아동');
insert into categories(name) values('생활/가공식품');
insert into categories(name) values('유아도서');
insert into categories(name) values('스포츠/레저');
insert into categories(name) values('여성잡화');
insert into categories(name) values('여성의류');
insert into categories(name) values('남성패션/잡화');
insert into categories(name) values('게임/취미');
insert into categories(name) values('뷰티/미용');
insert into categories(name) values('반려동물용품');
insert into categories(name) values('도서/티켓/음반');
insert into categories(name) values('식물');
insert into categories(name) values('기타 중고물품');